### PR TITLE
Porting to ROS2 (New PR)

### PR DESCRIPTION
**Pull request by RoboticsYY**
Hi @vrabaud, this package is depended by the packages of MoveIt2. since AcutronicRobotics cannot continue to support [PR#7](https://github.com/wg-perception/object_recognition_msgs/pull/7), this PR is a following effort along AcutronicRobotics' work to port this package to ROS2. Commit history of the original PR is reserved. Any new change requests can be addressed in this PR. PR#7 can be closed. 

Thanks!

### CODE REVIEW

**Comment by henningkayser** [comment]
@vrabaud could you give this a review?

**Comment by henningkayser** [comment]
@jonbinney tagging you because you pushed through with the Noetic release. We would like to get MoveIt 2 released for Foxy and depend on this branch to get released as well. I don't think the branch needs any fixup for this.

**Comment by jonbinney** [comment]
I looked briefly at the diff, and it looks reasonable. This would be the first time this package gets release to ros 2, right?

**Comment by henningkayser** [comment]
> I looked briefly at the diff, and it looks reasonable. This would be the first time this package gets release to ros 2, right?

Yeah, right. So probably we want to bump the version so that we don't run into conflicts with bloom. With the other packages we would just start at 2.x, would that work for you?

**Comment by jonbinney** [comment]
2.x sounds good to me.  I assume this PR isn't compatible with ROS1, so we'll need to merge it into a new branch for ros2, correct?

**Comment by henningkayser** [comment]
> 2.x sounds good to me. I assume this PR isn't compatible with ROS1, so we'll need to merge it into a new branch for ros2, correct?

Correct. Do you want to take care about bumping the version number or should I add it to this PR? Also, start with 2.0 or 2.4.2 matching the ROS1 version?

**Comment by jonbinney** [comment]
I can update the version when i do the release. I've created a "ros2" branch; @RoboticsYY or @henningkayser could one of you  retarget this PR to that branch?

**Comment by henningkayser** [comment]
@jonbinney I retargeted this branch in #11. We can probably close this one and #7

**Comment by jonbinney** [comment]
Closed in favor of https://github.com/wg-perception/object_recognition_msgs/pull/11

**Pull request closed without merging**
